# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - synthspeechmodel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1  # Enable BuildKit for potential efficiency improvements
      DOCKER_BUILDKIT_CACHE: 1  # Cache layers if applicable
    steps:
      - uses: actions/checkout@v4
      - name: Prune Docker Images (Optional)
        run: |
          docker image prune -f
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Prune Docker System (Optional)
        run: |
          docker system prune -f
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .  # Build context remains the same
          push: true
          tags: jobyjosh21/synthspeechmodel:latest, jobyjosh21/synthspeechmodel:${{ github.run_number }}  # Run number tag
          pull: true  # Ensure only necessary layers are pulled
          # Additional options for potential space optimization (see previous comment)






  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment:
  #     name: 'Production'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: python-app

  #     - name: Unzip artifact for deployment
  #       run: unzip release.zip

  #     - name: 'Deploy to Azure Web App'
  #       uses: azure/webapps-deploy@v2
  #       id: deploy-to-webapp
  #       with:
  #         app-name: 'synthspeechmodel'
  #         slot-name: 'Production'
  #         publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BEF0481564A54332B446FCA656A74838 }}
