# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - synthspeechmodel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1  # Enable BuildKit for potential efficiency improvements
      DOCKER_BUILDKIT_CACHE: 1  # Cache layers if applicable
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true  # Download LFS objects during checkout
      - name: Install Azure CLI
        uses: azure/CLI@v1
        with:
          azcliversion: 2.28.0  # Specify the version of Azure CLI to use
          inlineScript: |
            az --version
      - name: Download large file from Azure Blob Storage
        run: |
          sudo az storage blob download --account-name synthspeechmodel --account-key 2tYMclaD8PFFEckTUc5XVImKiECT454DaS7pqqHmj9eTU0vIOxuuXsBSy5Y0jnIB4F5t2/eW+WP++AStJM5/Dw== --container-name synthspeechmodel --name trained_random_forest_model_1000.pkl --file trained_random_forest_model_1000.pkl
      - name: Prune Docker Images (Optional)
        run: |
          docker image prune -f
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Prune Docker System (Optional)
        run: |
          docker system prune -f
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .  # Build context remains the same
          push: true
          tags: jobyjosh21/synthspeechmodel:latest, jobyjosh21/synthspeechmodel:${{ github.run_number }}  # Run number tag
          pull: true  # Ensure only necessary layers are pulled

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment:
  #     name: 'Production'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: python-app

  #     - name: Unzip artifact for deployment
  #       run: unzip release.zip

  #     - name: 'Deploy to Azure Web App'
  #       uses: azure/webapps-deploy@v2
  #       id: deploy-to-webapp
  #       with:
  #         app-name: 'synthspeechmodel'
  #         slot-name: 'Production'
  #         publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BEF0481564A54332B446FCA656A74838 }}
